AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyGoLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      ImageUri: lambda-apigateway:latest 
      Events:
        GetUsers:
          Type: HttpApi 
          Properties:
            Path: /users
            Method: GET
        GetUserById:
          Type: HttpApi
          Properties:
            Path: /users/{id}
            Method: GET
        CreateUser:
          Type: HttpApi
          Properties:
            Path: /users
            Method: POST
        UpdateUser:
          Type: HttpApi
          Properties:
            Path: /users/{id}
            Method: PUT

  MyApi:
    Type: AWS::Serverless::HttpApi 
    Properties:
      StageName: Prod
